/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import interfaz.logica.LogicaCarreras;
import interfaz.logica.LogicaCorredores;
import java.awt.Color;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Alvaro Perez
 */
public class Configuracion extends javax.swing.JDialog {

    private Timer timer;
    private String Ruta_Fichero;
    private LogicaCarreras logicaCarreras;
    private LogicaCorredores logicaCorredores;

    /**
     * Creates new form Configuracion
     */
    public Configuracion(java.awt.Frame parent, boolean modal, String Ruta_Fichero, LogicaCarreras logicaCarreras, LogicaCorredores logicaCorredores) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(95, 158, 160));
        this.Ruta_Fichero = Ruta_Fichero;
        this.logicaCarreras = logicaCarreras;
        this.logicaCorredores = logicaCorredores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldTiempo = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldTiempo.setText(org.openide.util.NbBundle.getMessage(Configuracion.class, "Configuracion.jTextFieldTiempo.text")); // NOI18N

        jCheckBox1.setText(org.openide.util.NbBundle.getMessage(Configuracion.class, "Configuracion.jCheckBox1.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(Configuracion.class, "Configuracion.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(Configuracion.class, "Configuracion.jLabel2.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(Configuracion.class, "Configuracion.jLabel3.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(Configuracion.class, "Configuracion.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jTextFieldTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean hola = jCheckBox1.isSelected();
        System.out.println(hola);
        //if (jCheckBox1.isSelected()) {
            actualizacion();
        //}
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldTiempo;
    // End of variables declaration//GEN-END:variables
public void actualizacion() {
        int tiempo = Integer.parseInt(jTextFieldTiempo.getText());
        System.out.println(tiempo);
        if (timer == null) {
            if (timer == null) {
                timer = new Timer();
                timer.schedule(new TimerTask() {
                    @Override
                    public void run() {
                        try {
                            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(Ruta_Fichero));
                            oos.writeObject(logicaCorredores);
                            oos.writeObject(logicaCarreras);
                            oos.close();
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        }
                        System.out.println("Autoguardado completado");
                    }
                },0, tiempo * 60000);

            } else {
                timer.cancel();
            }
            timer = new Timer();
            timer.schedule(new TimerTask() {
                @Override
                public void run() {
                    try {
                        ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(Ruta_Fichero));
                        oos.writeObject(logicaCorredores);
                        oos.writeObject(logicaCarreras);
                        oos.close();
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                    System.out.println("Autoguardado completado");
                }
            },0, tiempo * 60000);
        }
    }
}
