/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dto.Carreras;
import dto.Corredor;
import interfaz.logica.LogicaCarreras;
import interfaz.logica.LogicaCorredores;
import interfaz.logica.TablaParticipantes;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author alumnop
 */
public class ListaCorredoresCarrera extends javax.swing.JDialog {

    private LogicaCarreras logicaCarreras;
    private LogicaCorredores logicacorredores;
    private int seleccion;
    boolean finalizada;

    /**
     * Creates new form ListaCorredoresCarrera
     */
    public ListaCorredoresCarrera(java.awt.Dialog parent, boolean modal, LogicaCarreras lcarreras, LogicaCorredores logicacorredores, int seleccion, boolean finalizada) {
        super(parent, modal);
        getContentPane().setBackground(new Color(95, 158, 160));
        logicaCarreras = lcarreras;
        this.logicacorredores = logicacorredores;
        this.finalizada = finalizada;
        this.seleccion = seleccion;
        initComponents();
        rellenarTablaCorredores();
    }

    private void rellenarTablaCorredores() {
        if (finalizada) {
            Carreras carrera = logicaCarreras.getListaCarrerasFinalizadas().get(seleccion);
            jTableCorredores.setModel(new TablaParticipantes(carrera.getListaCorredores()));
        } else {
            Carreras carrera = logicaCarreras.getListaCarreras().get(seleccion);
            jTableCorredores.setModel(new TablaParticipantes(carrera.getListaCorredores()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAlta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCorredores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelAgregarparticipantes = new javax.swing.JLabel();
        jButtonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAlta.setText(org.openide.util.NbBundle.getMessage(ListaCorredoresCarrera.class, "ListaCorredoresCarrera.jButtonAlta.text")); // NOI18N
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jTableCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCorredores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCorredoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCorredores);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ListaCorredoresCarrera.class, "ListaCorredoresCarrera.jLabel1.text")); // NOI18N

        jLabelAgregarparticipantes.setText(org.openide.util.NbBundle.getMessage(ListaCorredoresCarrera.class, "ListaCorredoresCarrera.jLabelAgregarparticipantes.text")); // NOI18N

        jButtonBorrar.setText(org.openide.util.NbBundle.getMessage(ListaCorredoresCarrera.class, "ListaCorredoresCarrera.jButtonBorrar.text")); // NOI18N
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAgregarparticipantes)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabelAgregarparticipantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlta)
                    .addComponent(jButtonBorrar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        if (logicaCarreras.getListaCarreras().get(seleccion).getListaCorredores().size() < logicaCarreras.getListaCarreras().get(seleccion).getMaxparticipantes()) {
            Listaparticipantesacarrera lcc = new Listaparticipantesacarrera(this, true, seleccion, logicacorredores, logicaCarreras);
            lcc.setVisible(true);
            lcc.setLocationRelativeTo(null);
            rellenarTablaCorredores();
        } else {
            JOptionPane.showMessageDialog(this, "La carrera ya esta llena");
        }
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jTableCorredoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCorredoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCorredoresMouseClicked

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        int seleccion2 = jTableCorredores.getSelectedRow();
        logicaCarreras.getListaCarreras().get(seleccion).getListaCorredores().remove(seleccion2);
        rellenarTablaCorredores();
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    public JButton getjButtonAlta() {
        return jButtonAlta;
    }

    public JLabel getjLabelAgregarparticipantes() {
        return jLabelAgregarparticipantes;
    }

    public JButton getjButtonBorrar() {
        return jButtonBorrar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgregarparticipantes;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCorredores;
    // End of variables declaration//GEN-END:variables
}
