/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dto.Carreras;
import dto.Corredor;
import dto.Corredorcondorsal;
import interfaz.logica.LogicaCarreras;
import interfaz.logica.LogicaCorredores;
import interfaz.logica.TablaCarreras;
import interfaz.logica.TablaCorredores;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro Perez
 */
public class Listaparticipantesacarrera extends javax.swing.JDialog {

    LogicaCorredores lc;
    LogicaCarreras lca;
    private int carrera;
    private List<Corredor> corredoressininscritos;
    /**
     * Creates new form Listaparticipantesacarrera
     */
    public Listaparticipantesacarrera(java.awt.Dialog parent, boolean modal, int carrera, LogicaCorredores lc, LogicaCarreras lca) {
        super(parent, modal);
        initComponents();
        corredoressininscritos=new ArrayList();
        for (int i = 0; i < lc.getListaCorredores().size(); i++) {
            corredoressininscritos.add(lc.getListaCorredores().get(i));
        }
        setLocationRelativeTo(null);
        this.carrera = carrera;
        this.lc = lc;
        this.lca = lca;
        Carreras carreraseleccionada = lca.getListaCarreras().get(carrera);
     
        for (int i = 0; i < corredoressininscritos.size(); i++) {
            for (int a = 0; a < carreraseleccionada.getListaCorredores().size(); a++) {
                if ((corredoressininscritos.get(i).getDni().equalsIgnoreCase(carreraseleccionada.getListaCorredores().get(a).getCorredor().getDni()))) {
                    corredoressininscritos.remove(i);
                }

            }
        }
        jTable1.setModel(new TablaCorredores(corredoressininscritos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAñadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButtonAñadir.setText(org.openide.util.NbBundle.getMessage(Listaparticipantesacarrera.class, "Listaparticipantesacarrera.jButtonAñadir.text")); // NOI18N
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(Listaparticipantesacarrera.class, "Listaparticipantesacarrera.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAñadir)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAñadir)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        // TODO add your handling code here:
        int seleccion = jTable1.getSelectedRow();
        Corredor corredor = corredoressininscritos.get(seleccion);
        lca.getListaCarreras().get(carrera).inscribirparticipante(corredor);
        dispose();
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
