/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import interfaz.logica.LogicaCarreras;
import interfaz.logica.LogicaCorredores;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author alumnop
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    LogicaCorredores logicaCorredores;
    LogicaCarreras logicaCarreras;
    private static final String Ruta_Foto = "/img/imagencorredores.png";
    private static final String Ruta_Fichero = "datos.txt";
    File fichero;

    /**
     * Creates new form otra
     */
    public PantallaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(95, 158, 160));
        setIconImage(new ImageIcon(getClass().getResource(Ruta_Foto)).getImage());
        fichero = new File(Ruta_Fichero);
        logicaCorredores = new LogicaCorredores();
        logicaCarreras = new LogicaCarreras();
        jFoto.setIcon(new ImageIcon(getClass().getResource(Ruta_Foto)));
        readObject();
        writeObject();

        //UIManager.installLookAndFeel("EaSynthLookAndFeel",EaSynthLookAndFeel.class.getName());
        //cambiarlookandfeel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jFoto = new javax.swing.JLabel();
        jButtonConfiguracion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCorredor = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuCarrera = new javax.swing.JMenu();
        jMenuItemCarrera = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Liberation Mono", 1, 36)); // NOI18N
        jLabel1.setText("GESTION DE CARRERAS");

        jFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagencorredores.png"))); // NOI18N

        jButtonConfiguracion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonConfiguracion.setText("Configuracion");
        jButtonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfiguracionActionPerformed(evt);
            }
        });

        jMenuCorredor.setText("Corredor       ");

        jMenuItem1.setText("Lista Corredor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuCorredor.add(jMenuItem1);

        jMenuBar1.add(jMenuCorredor);

        jMenuCarrera.setText("Carrera");

        jMenuItemCarrera.setText("Lista Carrera");
        jMenuItemCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarreraActionPerformed(evt);
            }
        });
        jMenuCarrera.add(jMenuItemCarrera);

        jMenuBar1.add(jMenuCarrera);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jFoto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonConfiguracion)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButtonConfiguracion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ListaCorredor lc = new ListaCorredor(this, true, logicaCorredores);
        lc.setLocationRelativeTo(null);
        lc.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarreraActionPerformed
        // TODO add your handling code here:
        ListaCarreras lca = new ListaCarreras(this, true, logicaCorredores, logicaCarreras);
        lca.setLocationRelativeTo(null);
        lca.setVisible(true);
    }//GEN-LAST:event_jMenuItemCarreraActionPerformed

    private void jButtonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfiguracionActionPerformed
        // TODO add your handling code here:
        Configuracion configuracion = new Configuracion(this, true, Ruta_Fichero, logicaCarreras, logicaCorredores);
        configuracion.setLocationRelativeTo(null);
        configuracion.setVisible(true);
    }//GEN-LAST:event_jButtonConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfiguracion;
    private javax.swing.JLabel jFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCarrera;
    private javax.swing.JMenu jMenuCorredor;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemCarrera;
    // End of variables declaration//GEN-END:variables
/*public void cambiarlookandfeel(){

try{
             UIManager.setLookAndFeel(EaSynthLookAndFeel.class.getCanonicalName());
          SwingUtilities.updateComponentTreeUI(this);
         
         }
         catch(Throwable e){
         e.printStackTrace();
         JOptionPane.showConfirmDialog(this, "Error estableciendo Look And Feel");
         }


}*/
    public void setimagen() {
        setTitle("Gestion de Carreras");
        setIconImage(new ImageIcon(getClass().getResource(Ruta_Foto)).getImage().getScaledInstance(jFoto.getWidth(), jFoto.getHeight(), Image.SCALE_DEFAULT));
        this.getContentPane().setBackground(new Color(0, 0, 139));
        this.setLocationRelativeTo(null);
    }

    private void readObject() {
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream(Ruta_Fichero));
            logicaCorredores = (LogicaCorredores) ois.readObject();
            logicaCarreras = (LogicaCarreras) ois.readObject();
            ois.close();
        } catch (IOException io) {
            io.printStackTrace();
        } catch (ClassNotFoundException cnfe) {
            cnfe.printStackTrace();
        }
    }

    private void writeObject() {
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                try {
                    ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(Ruta_Fichero));
                    oos.writeObject(logicaCorredores);
                    oos.writeObject(logicaCarreras);
                    oos.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }
        );
    }
}
